### ISSUE TITLE
Customization of button styles

### ISSUE THREAD

**Issue by zgstyle** [trendmicro-frontend/react-buttons#5]
Could you please give an example how one can change text color of e.g. "Danger" button:
`<Button btnStyle="danger">Danger!</Button>`
using styled components.

**Comment by cheton** [comment]
You can use the CSS `[attribute*=value]` selector to match a specific class:

```js
const StyledButton = styled(Button)`
    &[class*="btn-danger---"] {
        background-color: #f00000;
        background-image: none;
        border-color: #ff0000;
    }
`;
```
